import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { Roboto_Mono, Poppins, Roboto } from "next/font/google"

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"],
  display: 'swap',
  variable: '--font-roboto',
})
const poppins = Poppins({
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"],
  display: 'swap',
  variable: '--font-poppins',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable} ${roboto.variable}`}>
        <Toaster />
        {children}
      </body>
    </html>
  );
}
